version: '3.9'

services:
  db:
    image: postgres
    container_name: go_bookings_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - go_bookings_postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: go_bookings_pgadmin
    depends_on:
      - db
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

volumes:
  go_bookings_postgres: